name: Markdown To HTML

on: 
  pull_request:
  push:
    branches:
      - "main"

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - run: |
          mkdir output
      - name: install pandoc
        run: sudo apt-get install pandoc
      - name: render markdowns
        run: for f in info/markdown/*.md ; do pandoc ${f} -f markdown -t html5 -s -o output/$(basename ${f}).html ; echo $(basename ${f} .md).html ; done
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'info/html'
          message: 'Proccessed markdown files'
          pull_strategy: 'NO-PULL'
          default_author: github_actions
